// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAN2tm6N7HAlXX2yQ6Sf8fCg7LO861wK_I',
    appId: '1:184514847044:web:afded650fdf1b8ecb53711',
    messagingSenderId: '184514847044',
    projectId: 'adminapplication-a3c94',
    authDomain: 'adminapplication-a3c94.firebaseapp.com',
    storageBucket: 'adminapplication-a3c94.appspot.com',
    measurementId: 'G-9QP5B5YSQK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAtnMwiB8bkEEUxrpv7Zia8AAxU22aVw9k',
    appId: '1:184514847044:android:a21f84085067444eb53711',
    messagingSenderId: '184514847044',
    projectId: 'adminapplication-a3c94',
    storageBucket: 'adminapplication-a3c94.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAJX34TFGUsuzff87hgCZpGS5bCdbpU0Mo',
    appId: '1:184514847044:ios:b107adee5c6924b9b53711',
    messagingSenderId: '184514847044',
    projectId: 'adminapplication-a3c94',
    storageBucket: 'adminapplication-a3c94.appspot.com',
    iosClientId: '184514847044-1a0fsi1uo5gjidblnspkgks2iei3jrjc.apps.googleusercontent.com',
    iosBundleId: 'com.example.adminapplication',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAJX34TFGUsuzff87hgCZpGS5bCdbpU0Mo',
    appId: '1:184514847044:ios:d7136aa4465077c6b53711',
    messagingSenderId: '184514847044',
    projectId: 'adminapplication-a3c94',
    storageBucket: 'adminapplication-a3c94.appspot.com',
    iosClientId: '184514847044-77pa4niffl13id050f1jqvuq3ktue7ol.apps.googleusercontent.com',
    iosBundleId: 'com.example.adminapplication.RunnerTests',
  );
}
